version: '3.4'

services:
  javi_api:
      container_name: javi_api
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - ENVIRONMENT=PROD
      ports:
        - 8081:8080
      networks:
        public_net:
          ipv4_address: 192.0.0.11

#  api_2:
#      container_name: api_2
#      build:
#        context: .
#        dockerfile: Dockerfile
#        args:
#          app_id: 2
#      environment:
#        - APPLICATION_ID=2
#      ports:
#        - 8082:8080
#      networks:
#        public_net:
#          ipv4_address: 192.0.0.12

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.0.0/24